In [6]:
import numpy as np
import pandas as pd
d={
    'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,2,3]
}
df=pd.DataFrame(d)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [7]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [8]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [9]:
df.dropna(axis=0)

     A    B  C
0  1.0  5.0  1

In [10]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [12]:
df.fillna(value='Filling Value')

               A              B  C
0            1.0            5.0  1
1            2.0  Filling Value  2
2  Filling Value  Filling Value  3

In [16]:
df=pd.DataFrame(d)
a=df['A'].fillna(value=df['A'].mean())
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [17]:
a

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [18]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [19]:
df.fillna
df['A'].fillna(value=df['A'].mean(),inplace=True)
df

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_18064\1210737360.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(value=df['A'].mean(),inplace=True)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

In [21]:
data={
    'Company':['Google','Google','MSFT', 'FB','FB','IBM'],
    'Person': ['Sam','Nihad','Any','Van','Rakib','Ovi'],
    'Sales': [200, 120, 340, 124, 243, 350]
}
df=pd.DataFrame(data)
df

  Company Person  Sales
0  Google    Sam    200
1  Google  Nihad    120
2    MSFT    Any    340
3      FB    Van    124
4      FB  Rakib    243
5     IBM    Ovi    350

In [40]:
byComp=df.groupby('Company')
byComp.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [31]:
byComp.sum()

           Person  Sales
Company
FB       VanRakib    367
Google   SamNihad    320
IBM           Ovi    350
MSFT          Any    340

  Company Person  Sales
0  Google    Sam    200
1  Google  Nihad    120
2    MSFT    Any    340
3      FB    Van    124
4      FB  Rakib    243
5     IBM    Ovi    350

In [33]:
byComp.std()

ValueError: could not convert string to float: 'Sam'

In [36]:
df.groupby('Company'.count()

_IncompleteInputError: incomplete input (699343721.py, line 1)

In [37]:
df

  Company Person  Sales
0  Google    Sam    200
1  Google  Nihad    120
2    MSFT    Any    340
3      FB    Van    124
4      FB  Rakib    243
5     IBM    Ovi    350

In [ ]:
df.